### ISSUE TITLE
phnt licence

### ISSUE THREAD

**Issue by dmex** [JustasMasiulis/nt_wrapper#2] opened 2018-08-13 19:15 UTC
Heya,

The files located in the /deps/phnt/ directory are missing both the original licence and attribution to their origin (as required by the licence)?

You'll need to include a link to the origin:
https://github.com/processhacker/processhacker/tree/master/phnt

Also the original licence:
https://github.com/processhacker/processhacker/blob/master/LICENSE.txt

Thanks 👍

**Comment by JustasMasiulis** [comment] 2018-08-13 19:42
First of all sorry for forgetting to credit the processhacker project.
The phnt headers are truly great, however it would be extremely handy if you guys made a separate GitHub repository for use as a submodule and if they used relative paths for easier integration with header only libraries.

Coming back to the actual issue, I have added links to process hacker and the headers in question to the readme and included a copy of the license inside the deps/phnt/ directory.

Hope that is sufficient.

**Comment by JustasMasiulis** [comment] 2018-08-16 12:01
@dmex I'll be closing this now as 3 days have passed. Hope the issue is resolved.

**Closed by JustasMasiulis** 2018-08-16 12:01 UTC

**Comment by dmex** [comment] 2018-10-02 22:30
@JustasMasiulis 

Sorry for taking a month to follow this up... 

> it would be extremely handy if you guys made a separate GitHub repository for use as a submodule

I've created a separate repository (https://github.com/processhacker/phnt) and we've changed the licence from GPL3 to the more permissive Creative Commons Attribution 4.0 International licence 😃

We had to review the code and discuss a few things before making those changes which required some time.

Hope it helps 👍 

-dmex

**Comment by JustasMasiulis** [comment] 2018-10-03 15:48
@dmex 

No worries about the response time.

I bet that the phnt repository will be extremely useful to many people - already have quite a few friends that will be taking use of it in both their current and future projects.
Concerning the license, from what I gathered the main change is that there is no need to distribute the source code if you make changes.

I'd also like to ask whether there would be any chances for a pull request, which makes phnt use relative paths for #includes, to be accepted? As far as I am aware such change wouldn't break existing code and allow one to simply add phnt as submodule and include it without touching any compiler directives.

Lastly I'd like to thank the process hacker team for all the effort 👍

**Comment by dmex** [comment] 2018-10-06 11:06
> Concerning the license, from what I gathered the main change is that there is no need to distribute the source code if you make changes.

Yep. You still need to mention any changes but you won't have to provide the sources.

> any chances for a pull request, which makes phnt use relative paths for #includes, to be accepted? As far as I am aware such change wouldn't break existing code and allow one to simply add phnt as submodule and include it without touching any compiler directives.

The issue with this is that it's supposed to be an SDK and including headers using a relative path makes it appear as if they're your own header and not something external. AFAIK relative paths can also cause some issues when you have two headers with the same name and you won't be able to do something like this if they were relative?

#include <myheader.h> <-- search path (external sdk)
#include "myheader.h" <-- current directory

**Comment by JustasMasiulis** [comment] 2018-10-06 13:35
> The issue with this is that it's supposed to be an SDK and including headers using a relative path makes it appear as if they're your own header and not something external.

Well I'd say not having to tinker with compiler stuff outweighs the chance of mistaking the headers with your own. An important thing to note is that the transition to relative paths only adds a choice. Projects that had the directory added to compilers include directories would continue to function and there is nothing stopping new projects to do the same.

> AFAIK relative paths can also cause some issues when you have two headers with the same name and you won't be able to do something like this if they were relative?
> `#include <myheader.h> <-- search path (external sdk)`
> `#include "myheader.h" <-- current directory`

As far as I know there shouldn't be anything wrong with this piece of code and it should work as expected.
Just to be sure I tested this using Visual Studio 2017 with both normal project (MSVC) and cmake project (clang).
`#include "Windows.h" // included the file in the same folder`
`#include <Windows.h> // included the actual windows SDK file`

nt_wrapper uses phnt headers that have the changes we are discussing applied to them. So far in several projects, both where it is added to the include paths and where it isn't, I haven't encountered any problems.

If there still are doubts about this change how about adding another branch? Although this has the cost of increased maintenance to sync up the changes.
